### ISSUE TITLE
'properties' element is not mandatory

### ISSUE THREAD

**Issue by Andersmholmgren** [sagold/json-schema-library#10]
https://github.com/sagold/json-schema-library/blob/master/lib/step.js#L28 assumes that schemas always have a 'properties' element. However this is not required in json schema

**Comment by sagold** [comment]
Thanks for pointing this out. I will fix this soon.

**Comment by sagold** [comment]
With v3.3.5 the issues is resolved. Thanks again!

**Comment by Andersmholmgren** [comment]
Thanks for the quick turnaround
