### ISSUE TITLE
Unable to iterate over schema using eachSchema

### ISSUE THREAD

**Issue by fizan2904** [sagold/json-schema-library#13]
I have used almost every utility in this library, and I like it very much.

While using the `eachSchema` method to iterate over schema I faced an issue. It will iterate only if the `type` keyword is not an array.

eg: { type: 'string' } works fine but { type: ['string', 'null'] } doesn't.

https://github.com/sagold/json-schema-library/blob/master/lib/schema/getTypeId.ts at line 24  `if (types[schema.type]) {` schema.type is assumed not to be an array everytime

**Comment by sagold** [comment]
Hi fizan,

thank you for the feedback. With version 6.0.0 `eachSchema` iterates over schemas defined with an _type-array_. Please pay attention to [api changes](https://github.com/sagold/json-schema-library#breaking-changes).

Are there any json-schema helpers you are missing here?
