### ISSUE TITLE
Cannot read properties of undefined (reading 'getRef')

### ISSUE THREAD

**Issue by TimBo93** [sagold/json-schema-library#15]
Hi,

thank you for your library!
We are using your library in order to create default-templates based on a schema.

At this point we are facing an issue:

```js
{
  $schema: 'http://json-schema.org/draft-04/schema#',
  version: 1.0,
  type: 'object',
  definitions: {
    saneUrl: {
      format: 'uri',
      pattern: '^https?://',
      default: 'https://localhost:8080',
    },
  },
  properties: {
    ContainerAddress: {
      $ref: '#/definitions/saneUrl',
    },
  },
}
```
regarding: https://www.jsonschemavalidator.net/ the schema itself should be valid.

```typescript
import { Draft04 as JsonSchemaLibrary } from 'json-schema-library';

const schema = {
  $schema: 'http://json-schema.org/draft-04/schema#',
  version: 1.0,
  type: 'object',
  definitions: {
    saneUrl: {
      format: 'uri',
      pattern: '^https?://',
      default: 'https://localhost:8080',
    },
  },
  properties: {
    ContainerAddress: {
      $ref: '#/definitions/saneUrl',
    },
  },
};

export const jsonSchemaToTemplateConverter = () => {
  const data = {
    AnalyticsContainerAddress: 'https://asdf',
  };

  const jsonSchema = new JsonSchemaLibrary();
  const result = jsonSchema.getTemplate({}, schema);
  return result;
};
```

`getTemplate` throws the following exception:
`TypeError: Cannot read properties of undefined (reading 'getRef')`

Are we missing something?

Kind regards
Tim

**Comment by TimBo93** [comment]
We were able to solve the issue by calling

```typescript
const jsonSchema = new JsonSchemaLibrary();
jsonSchema.setSchema(schema);
return getTemplate(jsonSchema, data);
```

What I have reported may not a bug, but more likely a misunderstanding in the API. I was confused that it only fails when using $ref.

**Comment by sagold** [comment]
Hi @TimBo93 thank you for the feedback. 



I will update the documentation about this and think about api improvements.

Cheers,
Sascha

**Comment by sagold** [comment]
Documentation has been updated and latest api changes should prevent some of thise errors.
