### ISSUE TITLE
Add missing support for `dependencies` in `getSchema`

### ISSUE THREAD

**Issue by benjdlambert** [sagold/json-schema-library#19]
Hey :wave:

I wonder if theres a different way to do this, but it looks like that I'm unable to get the schema for something that is defined in `dependencies`.

Say I have a schema that looks like the following:

```js
const parsed = new Draft07({
  title: "Fill in some steps",
  required: [
    "name"
  ],
  properties: {
    name: {
      title: "Name",
      type: "string",
      description: "Unique name of the component"
    },
    generation: {
      type: "string",
      title: "Generation Method",
      enum: [
        "Hide Custom Field",
        "Display Custom Field"
      ],
      default: "Hide Custom Field"
    }
  },
  dependencies: {
    generation: {
      oneOf: [
        {
          properties: {
            generation: {
              const: "Hide Custom Field"
            }
          }
        },
        {
          required: [
            "customField"
          ],
          properties: {
            generation: {
              const: "Display Custom Field"
            },
            customField: {
              title: "Custom Field",
              type: "string"
            }
          }
        }
      ]
    }
  }
})
```

And then if I do `parsed.getSchema('#/customField', { generation: 'Display Custom Field' })` I get `Could not find a valid schema for property '#/customField' within object` where as it should be part of the json schema for validation. Is there something I'm missing here or a way to get back the schema `{ type: string }` for this bit in the schema?

Thanks!

**Comment by sagold** [comment]
Hi!

Unfortunately, dependencies is not yet implemented in getTemplate. I will add this.

Cheers.

**Comment by sagold** [comment]
Hi!

I will need to investigate this. Your example looks quite tricky.

**Comment by sagold** [comment]
short update: dependencies is currently only part of validation and not interpreted in other helper functions. Will need to add this to the general step-resolver as is done with anyOf, oneOf etc.

**Comment by sagold** [comment]
Hi Ben,

with version v6.1.0 support for _dependencies_ has been added to _getTemplate_ and _getSchema_. For your above example the following will work out of the box:

```js
getSchema('#/customField', { generation: 'Display Custom Field', customField: "with-value" });
// { type: "string", title: "Custom Field" }
```
https://github.com/sagold/json-schema-library/blob/master/test/unit/issues/issue19.getSchema.dependencies.test.ts#L56

to retrieve the schema without passing a value for `customField` you need to change the _oneOf_ resolution behaviour like so:

```js
import { Draft07, resolveOneOfFuzzy } from "json-schema-library";
const core = new Draft07(schema);
core.resolveOneOf = function resolveOneOf(data, schema: JSONSchema, pointer: JSONPointer) {
    return resolveOneOfFuzzy(this, data, schema, pointer);
};

core.getSchema('#/customField', { generation: 'Display Custom Field' });
// { type: "string", title: "Custom Field" }
```
https://github.com/sagold/json-schema-library/blob/master/test/unit/issues/issue19.getSchema.dependencies.test.ts#L69

Per default, _oneOf_-options have to be strictly validated with the input value. In this case, all _oneOf_ are invalid and return an error. The resolver _resolveOneOfFuzzy_ instead will decide on a specific _oneOf_-schema and return this.

In my experience, working with a user interface supporting _oneOf_ selection, you know exactly, which _oneOf_ schema should be selected based on the input data. In your case, this is a selection based on a value for `generation`. In this case and using the _resolveOneOfFuzzy_ you can add a property `oneOfProperty` which will use this property and its value to select a _oneOf_ entry:

```json
"dependencies": {
    "generation": {
      "oneOfProperty": "generation",
      "oneOf": [
        ...
      ]
   }
}
```
https://github.com/sagold/json-schema-library/blob/master/test/unit/issues/issue19.getSchema.dependencies.test.ts#L29

I do hope this helps and explains why _oneOf_ resolution requires a little help here. Right now, replacing the _resolveOneOf_ resolver requires a complete custom Core or the workaround above. I will rewrite the Core api next to support simpler configuration of such things.

With this, I close the issue. Feel free to ask or reopen this issue if it is not working.

Cheers.

**Comment by benjdlambert** [comment]
Nice! Thank you so much! Will give this a try out! :tada:
