### ISSUE TITLE
Undefined behavior when a schema's "type" is an array of types

### ISSUE THREAD

**Issue by Lange** [sagold/json-schema-library#2]
Hello! :wave:

In a few of my JSON Schemas, I specify an array of valid `type`s, such as:
```json
"type": ["object", "null"]
```

This is indeed valid JSON Schema syntax, but this library currently has undefined behavior when `type` is an array, and as such it ends up always rejecting the provided value.

Aside from this one issue, this library has been super helpful and I'm using it in some fun projects. Thanks for making it! :heart:

**Comment by Lange** [comment]
The undefined behavior arises from [validate.js#L33](https://github.com/sagold/json-schema-library/blob/master/lib/validate.js#L33), which only checks for strict equality of the provided `type` against the schema's `type`. This is inadequate for scenarios where the schema's `type` is an array of types.

**Comment by sagold** [comment]
Hello.

Yes indeed, some draft04 features are still missing, but now its one less. Thank you for your contributions. Super helpful is the purpose of this library. I am glad it does its job.

Your changes and a fix in your conditional has been released with version `v2.4.0`.

Regards.
sagold
