### ISSUE TITLE
Yarn 3 YN0001- Error while persisting 

### ISSUE THREAD

**Issue by pedronastasi** [sagold/json-schema-library#20]
I'm getting YN0001- Error while persisting.... on windows when I run yarn install . Version Yarn 3.2.3

It occurs during the linking process. I'm using node-modules linker.

`
➤ YN0001: │ Error: While persisting /C:/Users/.../AppData/Local/Yarn/Berry/cache/json-schema-library-npm-7.2.0-542ab2e6c3-8.zip/node_modules/json-schema-library/ -> /C:/Users/...backstage/node_modules/json-schema-library ENOENT: no such file or directory, open 'C:\Users\PNastasi\Documents\eg-group\backstage\node_modules\json-schema-library\profiles\develop-doValidations-2022-09-28 15:37:34.txt'
`

I created this issue before in yarn  in the following link: https://github.com/yarnpkg/berry/issues/4985. and their verdict it was cause to the colon in the file that is not allowed on windows https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions:~:text=except%20for%20the,%3A%20(colon)

**Comment by sagold** [comment]
Hi pedronastasi,

there was indeed a profile output published to npm. I have removed the file and excluded it from publishing. You have a clean package available with `v7.2.1`.

Can you verify that this solves your issue?

Cheers.

**Comment by pedronastasi** [comment]
Yes, It is solved
