### ISSUE TITLE
Type 'number' accepts null/NaN as value

### ISSUE THREAD

**Issue by MueckeMa** [sagold/json-schema-library#23]
Hi,
when validating a value of type `number`, `null` or `NaN` are assumed as valid value. If the type `integer` is validated, this error message appears:

>  Expected `NaN` (number) in `#` to be of type `integer`

Expected behavior:

When checking the type `number`, this error message is generated for a value of  `null` or `NaN`:

> Expected `NaN` (number) in `#` to be of type `number`

Schema
```js
{
   type: 'number'
}
```
Value
```js
null
```

Version: [v7.3.2](https://github.com/sagold/json-schema-library/releases/tag/v7.3.2)

**Comment by sagold** [comment]
Thank you for reporting this.

A fix has been published with `v7.3.3` treating NaN as valid integer: 
https://github.com/sagold/json-schema-library/runs/9641080742#r0s23

Cheers
