### ISSUE TITLE
Clearly document how remote schemas are identified

### ISSUE THREAD

**Issue by Carl-Foster** [sagold/json-schema-library#28]
Our schemas are mostly defined for file-based access and we utilise the library for stitching together the schemas. We found a fair bit of hassle with the way the remote schemas were keyed when adding through `addRemoteSchema`.

```
{
    "$id": "OurCoolSchema.json"
}

{
    "$id": "ConsumerSchema.json",
    "properties": {
        "referenced": {
             "$ref": "OurCoolSchema.json"
        }
    }
}
```

To have this properly resolve, its needed to do `draft.addRemoteSchema("ConsumerSchema.json/OurCoolSchema.json", OurCoolSchema)`. This isn't documented anywhere and it took quite a bit of searching to get this right. This is a common issue we have found with json-schema libraries, but a nice note about how the resolution works would be appreciated.

**Comment by Carl-Foster** [comment]
Note I am happy to contribute a fix for this.

**Comment by sagold** [comment]
Hi Carl.

Thank you for spotting issues in the README. Happy to update the usage of remote schemas. Feedback on the upcoming update is highly appreaciated.

Sascha

**Comment by sagold** [comment]
Hi Carl,

I updated the description and examples of `addRemoteSchema`. I hope its becoming obvious on how to work with remote references. As said, any feedback is highly welcome.

https://github.com/sagold/json-schema-library/tree/develop#addremoteschema

Cheers,
Sascha
