### ISSUE TITLE
ESM-Bundle for using in browser

### ISSUE THREAD

**Issue by lqdchrm** [sagold/json-schema-library#29]
Thanks a lot for this library, which I plan to use for model-validation in the browser.

Currently I'm a bit stuck, because I can't use the es6-bundle inside `dist/module`. The generated code imports files without file-extension `.js`, but this would be needed for browser imports.

Ideally, everything would be bundles into a single `jsonSchemaLibrary.esm.min.js.`

I can give it a try and add a bundle-script in package.json using esbuild.

**Comment by sagold** [comment]
Closing this along with https://github.com/sagold/json-schema-library/issues/51. Thank you for your efforts @lqdchrm!
