### ISSUE TITLE
getTemplate loses compiled references

### ISSUE THREAD

**Issue by Carl-Foster** [sagold/json-schema-library#31]
We continue to have issues with `getTemplate` erroring out when we have referenced schemas. It appears that within the `createTemplateSchema` there are a number of copy / merge functions which lose the non-enumerable properties which have been compiled into the schema. This causes the `getRoot` function to not exist and instead of properly referencing the actual compiled schema, it instead tries to find the definitions from the `core.rootSchema`.

**Comment by sagold** [comment]
Hi.

Can you share an example of your setup (e.g. using addRemoteSchema, specific schemas) and which $refs fail?

Thank you!

**Comment by sagold** [comment]
Your [fix](https://github.com/sagold/json-schema-library/pull/35) has been published with `json-schema-library@7.4.8` and resolves this issue.

Thank you very much!
