### ISSUE TITLE
Cannot be used in browser-based applications that set a CSP which disallows unsafe-eval

### ISSUE THREAD

**Issue by snoozbuster** [sagold/json-schema-library#39]
See https://github.com/lys-lang/node-ebnf/issues/48 for additional context. the `ebnf` package used by `json-query` cannot be used in browser-based applications with CSPs that restrict the use of `eval`.

**Comment by snoozbuster** [comment]
This has been fixed in `node-enbf@1.9.1` - [see here](https://github.com/lys-lang/node-ebnf/releases/tag/1.9.1). Could json-query and this package be updated to pick up that updated version?

**Comment by sagold** [comment]
Thank you both for this update. json-query and its ebnf dependency has been updated and published. A corresponding update of json-schema-library will follow.

**Comment by sagold** [comment]
With 

- `json-schema-library@7.4.9` and
- `json-schema-library@8.0.0-rc6`

dependencies use `ebnf@1.9.1`. Can you verify that this solves your issue?

Cheers.
sagold
