### ISSUE TITLE
Support for `idn-email` fromat in Draft07

### ISSUE THREAD

**Issue by heikoter** [sagold/json-schema-library#45]
Hello,
I am not sure if I am missing something or does something the wrong way.
https://json-schema.org/draft-07/json-schema-release-notes.html
From the documentation, it is said, that with Draft07 the format support for `idn-email` should be given.
Is there a way to add this format? We would be super happy to have the support.
Thanks

**Comment by sagold** [comment]
Hi Heiko,

support for `format: "id-email"` has been added with `json-schema-library@9.1.0`.

Cheers.
